### ISSUE TITLE
Why student has no courses is showing when i try to enter attendence

### ISSUE THREAD

**Issue by bishal01** [samarth-p/College-ERP#10]

**Comment by Anjan112** [comment]
![Capture](https://user-images.githubusercontent.com/77722979/111918174-defa8c00-8aa9-11eb-9766-db38fd417deb.PNG)


It shows a student has no courses when trying to enter attendance!!
This is probably because:
If you have assigned a teacher to a particular class and course and no students have enrolled in the course this can occur..
For what teacher did you get this error???
